const strings = [
    "Swap bags with player in 1st for this hole",
  "Create a mando for everyone (including you)",
  "Forehand drive, Turbo putt",
  "Choose one disc to use for the entire hole from an opponent's bag",
  "Must putt with your back to the basket",
  "Drive: red disc. Approach: white disc. Putt blue disc (anyone's bag)",
  "Wear your bag for the entire hole.",
  "Drive with your disc upside down.",
  "Overhand drive",
  "Must use one forehand and one backhand on this hole.",
  "Weak hand putt",
  "Weak hand drive",
  "Drive must be a roller and putt must be a turbo.",
  "Approach shot with upside-down disc.",
  "Weak hand sidearm drive.",
    "Must throw a thumber on either drive or upshot",
  "You get 10 steps forward from tee box and from each lie.",
  "An opponent picks a disc from your bag for each of your throws.",
  "Pick a disc from an opponent's bag for each of your throws.",
  "Putt with your disc upside down.",
  "Drive with your mini.",
  "Drive with your weak hand.",
  "Drive with your most overstable disc.",
  "Play the hole however you want.",
  "Sidearm for every throw this hole",
  "You can heckle one opponent this hole.",
  "Drive with a disc from your opponent's bag.",
  "Drive must be a roller.",
  "Person with the worst score gives you a mando.",
  "Under the leg putt.",
  "Choose one disc from opponent's bag to use for entire hole.",
  "Drive with a putter.",
  "Putt with a driver.",
  "Drive with your most understable disc.",
  "Scream \"NICE ONE, BRO!\" when each person drives.",
  "Opponent chooses a disc for you to drive with",
    "Drive must be a hyzer.",
    "Drive must be anhyzer."
];
